#without docker-compose i have to manually run multiple lines of docker commands in cli
version: '3.8'
services:
  postgres:
    image: postgres:17.2
    container_name: container_psql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Mozart90-
      POSTGRES_DB: mas_tables
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  postgres_data:
